#!/usr/bin/env python3
"""Generate docs/Z-DESKTOP-TASKS.md — the engineering task ledger.

Deterministic: same inputs → same output. Every task has:
id, title, milestone, domain, status, deps, notes.
Statuses use the canonical vocabulary (IMPLEMENTED/PARTIAL/PLANNED/RESEARCH).
"""
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "docs", "Z-DESKTOP-TASKS.md")

# (domain_key, domain_title, [(task_suffix, title, deps_suffixes, status)])
# deps reference ids within the same domain unless prefixed with another key.
DOMAINS = [
    ("core", "Agent Core & Runtime", [
        ("001", "Turn loop hardening: all exit paths persist thread", [], "PARTIAL"),
        ("002", "Mid-run cancellation flag inside sandbox wait loop", ["003"], "PLANNED"),
        ("003", "Sandbox wait-loop refactor for cancel checks", [], "PLANNED"),
        ("004", "Steering queue state in Shared", ["020"], "IMPLEMENTED"),
        ("005", "EnqueueMessage command + SteeringQueued event", ["004"], "IMPLEMENTED"),
        ("006", "drain_steering between tool rounds", ["005"], "IMPLEMENTED"),
        ("007", "Steering combine gate (merge consecutive texts)", ["006"], "IMPLEMENTED"),
        ("008", "Cancel clears steering queue on turn end", ["006"], "IMPLEMENTED"),
        ("009", "PauseTurn command + checkpoint capture", ["041"], "PLANNED"),
        ("010", "ResumeTurn from checkpoint", ["009"], "PLANNED"),
        ("011", "MAX_TOOL_ROUNDS configurable via settings", ["set-002"], "IMPLEMENTED"),
        ("012", "Approval timeout setting wired to gate deadline", ["set-003"], "IMPLEMENTED"),
        ("013", "Doom-loop breaker (identical failing calls)", ["014"], "IMPLEMENTED"),
        ("014", "Per-turn tool-call fingerprint counter", [], "IMPLEMENTED"),
        ("015", "Doom-loop threshold setting", ["013", "set-002"], "PLANNED"),
        ("016", "Provider retry classification (network/429/5xx/auth)", [], "IMPLEMENTED"),
        ("017", "Retry-After honoring for 429", ["016"], "IMPLEMENTED"),
        ("018", "Byte-identical retry payloads", ["016"], "IMPLEMENTED"),
        ("019", "Retry journaling (attempt field)", ["016"], "IMPLEMENTED"),
        ("020", "Protocol extension: EnqueueMessage/Pause/Resume variants", [], "IMPLEMENTED"),
        ("021", "Multi-thread UI wiring (thread list panel)", ["ui-030"], "IMPLEMENTED"),
        ("022", "Thread rename/delete/duplicate commands", ["021"], "IMPLEMENTED"),
        ("023", "Thread delete tombstone in journal", ["022", "jour-001"], "IMPLEMENTED"),
        ("024", "Active-turn delete rejection", ["022"], "PLANNED"),
        ("025", "Startup auto-open most recent thread", ["021"], "PARTIAL"),
        ("026", "Corrupt-thread skip surfaced in thread list", ["021"], "IMPLEMENTED"),
        ("027", "build_request perf benchmark (1k-msg history)", [], "PLANNED"),
        ("028", "Command→TurnStarted latency benchmark", [], "PLANNED"),
        ("029", "EventQueue drain benchmark (1k events)", [], "PLANNED"),
        ("030", "Runtime soak test harness (memory/thread growth)", [], "PLANNED"),
        ("031", "Provider failover hook points (router-ready)", ["prov-004"], "PLANNED"),
        ("032", "Turn-scoped tracing spans (turn_id correlation)", [], "PLANNED"),
        ("033", "Tool-call args hashing utility", [], "PLANNED"),
        ("034", "Structural validity assertion in build_request tests", [], "PLANNED"),
        ("035", "Clean-boundary trim fuzz test (random histories)", [], "PLANNED"),
        ("036", "Approval denial reason surfaced to model", [], "PLANNED"),
        ("037", "Cancellation reason recorded in TurnFinished", [], "PLANNED"),
        ("038", "Streaming delta coalescing under event flood", [], "PLANNED"),
        ("039", "Bounded event queue with drop policy + diagnostics", ["038"], "PLANNED"),
        ("040", "Turn worker panic containment (catch_unwind boundary)", [], "PLANNED"),
        ("041", "Checkpoint record type + journal kind", ["jour-001"], "PLANNED"),
        ("042", "Checkpoint restore path in start_turn", ["041"], "PLANNED"),
        ("043", "Crash-recovery E2E: kill mid-turn → resume", ["042", "jour-003"], "PLANNED"),
        ("044", "Context overflow refusal message (ZD-E-0050)", [], "PLANNED"),
        ("045", "trim→compact escalation order implemented", ["ctx-004"], "PLANNED"),
    ]),
    ("jour", "Journal & Durable Execution", [
        ("001", "Journal record schema + writer skeleton", [], "IMPLEMENTED"),
        ("002", "O_APPEND append + fsync policy (every N records)", ["001"], "IMPLEMENTED"),
        ("003", "Segment rotation at 16 MiB + CURRENT pointer", ["002"], "PLANNED"),
        ("004", "Segment checksum trailer (fnv1a64)", ["003"], "PLANNED"),
        ("005", "Replay engine core (ordered segment read)", ["001"], "IMPLEMENTED"),
        ("006", "Reducer registration API", ["005"], "IMPLEMENTED"),
        ("007", "Threads view reducer", ["006"], "IMPLEMENTED"),
        ("008", "Task view reducer", ["006"], "IMPLEMENTED"),
        ("009", "Usage stats reducer", ["006"], "PLANNED"),
        ("010", "Seq gap tolerance + warning", ["005"], "IMPLEMENTED"),
        ("011", "Corrupt tail truncation repair", ["005"], "IMPLEMENTED"),
        ("012", "Deterministic double-replay equality test", ["007", "008"], "PLANNED"),
        ("013", "Background compaction (fold old segments)", ["004"], "PLANNED"),
        ("014", "Compaction snapshot hash verification", ["013"], "PLANNED"),
        ("015", "Journal redaction by construction", ["001", "red-002"], "PLANNED"),
        ("016", "journal_lag_records metric", ["002"], "PLANNED"),
        ("017", "Fixture journal-seq generation script", [], "PLANNED"),
        ("018", "SQLite-vs-JSONL decision ADR with load data", ["027"], "RESEARCH"),
        ("019", "Journal perf benchmark (10k records append+replay)", ["003"], "PLANNED"),
        ("020", "Crash-injection test: kill during append", ["002"], "PLANNED"),
        ("021", "CheckpointCreated event emission", ["core-041"], "PLANNED"),
        ("022", "TaskStateChanged journal events", ["orch-001"], "PLANNED"),
        ("023", "EvidenceRecorded journal events", ["sup-001"], "PLANNED"),
        ("024", "command_received/turn_started lifecycle records", ["001"], "IMPLEMENTED"),
        ("025", "provider_called records with attempt field", ["001", "core-019"], "PLANNED"),
        ("026", "tool_approved/tool_executed records", ["001"], "PLANNED"),
        ("027", "Load-test fixture: 1M-record synthetic journal", ["017"], "PLANNED"),
        ("028", "error_observed records", ["001"], "PLANNED"),
        ("029", "message_persisted records", ["001"], "IMPLEMENTED"),
        ("030", "ReplaySummary log event", ["005"], "PLANNED"),
    ]),
    ("idx", "Repository Intelligence", [
        ("001", "Index actor thread + channel API", [], "IMPLEMENTED"),
        ("002", "Snapshot read semantics (no shared mutable state)", ["001"], "IMPLEMENTED"),
        ("003", "Tree-sitter dependency evaluation ADR", [], "IMPLEMENTED"),
        ("004", "Rust grammar language pack", ["003"], "IMPLEMENTED"),
        ("005", "TypeScript/JavaScript grammar pack", ["003"], "PLANNED"),
        ("006", "Python grammar pack", ["003"], "PLANNED"),
        ("007", "Symbol extraction queries (fn/class/method/struct)", ["004"], "PLANNED"),
        ("008", "Reference extraction queries", ["004"], "PLANNED"),
        ("009", "Import edge extraction queries", ["004"], "PLANNED"),
        ("010", "Symbol id scheme (file_hash:name:kind:index)", ["007"], "PLANNED"),
        ("011", "Fingerprint store (content hash per file)", [], "PLANNED"),
        ("012", "Incremental reparse on change", ["011", "wat-001"], "PLANNED"),
        ("013", "Incremental parity test vs full rebuild", ["012"], "PLANNED"),
        ("014", "Reverse-reference index", ["008"], "PLANNED"),
        ("015", "Affected-analysis query (edit X → impacted)", ["014"], "PLANNED"),
        ("016", "Parser panic containment (catch_unwind per file)", ["004"], "PLANNED"),
        ("017", "Errored-file registry + grammar-upgrade retry", ["016"], "PLANNED"),
        ("018", "Trigram index structure", [], "PLANNED"),
        ("019", "Trigram incremental postings update", ["018", "012"], "PLANNED"),
        ("020", "Lexical search query path (intersect+verify)", ["018"], "PLANNED"),
        ("021", "Search p95 <200ms benchmark on medium fixture", ["020", "fix-002"], "PLANNED"),
        ("022", "Spill-to-disk postings for XL corpora", ["019"], "PLANNED"),
        ("023", "Repo-map v2 scorer (centrality×recency×terms)", ["015"], "PLANNED"),
        ("024", "Repo-map v2 token-budget packing", ["023"], "PLANNED"),
        ("025", "Repo-map byte-stability test", ["024"], "PLANNED"),
        ("026", "Index open benchmark (1k files <2s)", ["001", "fix-001"], "PLANNED"),
        ("027", "Incremental reindex <50ms benchmark", ["012"], "PLANNED"),
        ("028", "Lookup <10ms benchmark", ["014"], "PLANNED"),
        ("029", "100k-file index throughput benchmark", ["fix-003"], "PLANNED"),
        ("030", "Memory cap + spill path stress test", ["022"], "PLANNED"),
        ("031", "Go-to-definition tool (agent-facing)", ["014"], "PLANNED"),
        ("032", "Find-references tool (agent-facing)", ["014"], "PLANNED"),
        ("033", "Call-graph extraction (Rust first)", ["007", "008"], "PLANNED"),
        ("034", "Dependency graph export for diagram engine", ["033"], "PLANNED"),
        ("035", "Index actor metrics (throughput, queue depth)", ["001"], "PLANNED"),
        ("036", "Watcher-driven live updates end-to-end", ["012", "wat-001"], "PLANNED"),
        ("037", "fixture tiny-repo committed", [], "PLANNED"),
        ("038", "fixture medium-repo generator script", ["fix-002"], "PLANNED"),
        ("039", "fixture large-repo generator script", ["fix-003"], "PLANNED"),
        ("040", "fixture xl-repo generator script", ["fix-004"], "PLANNED"),
    ]),
    ("edit", "Safe Editing Engine", [
        ("001", "Fingerprint computation (fnv1a64) utility", [], "IMPLEMENTED"),
        ("002", "fs_read records fingerprint per thread", ["001"], "IMPLEMENTED"),
        ("003", "Stale-write refusal (ZD-E-0060)", ["002"], "IMPLEMENTED"),
        ("004", "Atomic write helper (temp+rename+fsync)", [], "IMPLEMENTED"),
        ("005", "fs_write routes through atomic helper", ["004"], "IMPLEMENTED"),
        ("006", "Crash-simulation test for atomic writes", ["004"], "PLANNED"),
        ("007", "Concurrent-reader sees old-or-new test", ["004"], "PLANNED"),
        ("008", "edit_patch tool definition + schema", ["003"], "IMPLEMENTED"),
        ("009", "Patch block exact-match application", ["008"], "IMPLEMENTED"),
        ("010", "Whitespace-normalized fallback with warning", ["009"], "IMPLEMENTED"),
        ("011", "Missing-anchor clean failure (ZD-E-0061)", ["009"], "IMPLEMENTED"),
        ("012", "Multi-block sequential application", ["009"], "IMPLEMENTED"),
        ("013", "Whole-patch abort on any failure", ["012"], "IMPLEMENTED"),
        ("014", "Rollback staging (old bytes captured)", ["012"], "IMPLEMENTED"),
        ("015", "Rollback spill-to-temp for large ops", ["014"], "PLANNED"),
        ("016", "Write grants registry (exclusive per file)", [], "IMPLEMENTED"),
        ("017", "Grant overlap rejection at grant time", ["016"], "IMPLEMENTED"),
        ("018", "No-fingerprint flag on blind writes", ["002"], "PLANNED"),
        ("019", "Diff generation (histogram algorithm)", [], "PLANNED"),
        ("020", "Patience fallback for noisy files", ["019"], "PLANNED"),
        ("021", "Binary file diff placeholder", ["019"], "PLANNED"),
        ("022", "git_status read tool", [], "IMPLEMENTED"),
        ("023", "git_diff read tool", ["022"], "IMPLEMENTED"),
        ("024", "git_log read tool", ["022"], "IMPLEMENTED"),
        ("025", "git library vs shell-out decision ADR", [], "IMPLEMENTED"),
        ("026", "git_add/git_commit write tools (approved)", ["025"], "PLANNED"),
        ("027", "git_branch write tool", ["026"], "PLANNED"),
        ("028", "History-rewrite prohibition enforcement tests", ["026"], "PLANNED"),
        ("029", "User-edit preservation check before agent overwrite", ["003"], "PLANNED"),
        ("030", "Staged multi-file op transaction type", ["014"], "PLANNED"),
    ]),
    ("orch", "Orchestration & Sub-Agents", [
        ("001", "Task record store (create/transition/query)", ["jour-008"], "IMPLEMENTED"),
        ("002", "Task dependency resolution (ready-set computation)", ["001"], "IMPLEMENTED"),
        ("003", "Orchestrator loop thread", ["002"], "IMPLEMENTED"),
        ("004", "Budget enforcer (tokens/time per task)", ["001"], "IMPLEMENTED"),
        ("005", "Sub-agent spawn policy validation", ["003"], "PLANNED"),
        ("006", "Isolation ladder levels (context/scope/worktree/sandbox)", ["005"], "PLANNED"),
        ("007", "Worktree manager create/list/cleanup", ["edit-026"], "PLANNED"),
        ("008", "Worktree orphan scan at startup", ["007"], "PLANNED"),
        ("009", "Dirty-worktree quarantine on cleanup", ["007"], "PLANNED"),
        ("010", "Result evidence verification (parent-side)", ["sup-003"], "PLANNED"),
        ("011", "Child failure isolation (parent unaffected)", ["005"], "PLANNED"),
        ("012", "Concurrency caps (global + per-parent)", ["003"], "PLANNED"),
        ("013", "Best-of-N runner", ["007", "010"], "PLANNED"),
        ("014", "Evaluator scoring rubric implementation", ["013"], "PLANNED"),
        ("015", "Loser-attempt archival as artifacts", ["013", "art-001"], "PLANNED"),
        ("016", "Merge-via-safe-editing pipeline", ["007", "edit-030"], "PLANNED"),
        ("017", "Conflict surface (never auto-resolve)", ["016"], "PLANNED"),
        ("018", "TaskStateChanged events to UI", ["001"], "PLANNED"),
        ("019", "Task graph visualization data export", ["002"], "PLANNED"),
        ("020", "Budget exhaustion handling (pause vs fail policy)", ["004"], "PLANNED"),
        ("021", "Spawn policy settings (dev mode)", ["005", "set-002"], "PLANNED"),
        ("022", "Reference-passed shared context (no duplication)", ["005"], "PLANNED"),
        ("023", "Parent-evaluated result contract tests", ["010"], "PLANNED"),
        ("024", "Orchestrator crash recovery (resume ready tasks)", ["003", "jour-005"], "IMPLEMENTED"),
        ("025", "Best-of-N budget cap enforcement test", ["013"], "PLANNED"),
    ]),
    ("sup", "Supervision & Evidence", [
        ("001", "Evidence record types (Build/Tests/Diff/Bench/Regression)", [], "IMPLEMENTED"),
        ("002", "Capture hook: sandbox exit codes → Build evidence", ["001"], "IMPLEMENTED"),
        ("003", "Capture hook: test-runner output parsing", ["001"], "IMPLEMENTED"),
        ("004", "Capture hook: fs_write/edit_patch diffs", ["001", "edit-019"], "IMPLEMENTED"),
        ("005", "Claim regex set (conservative success phrases)", [], "IMPLEMENTED"),
        ("006", "Claim-to-evidence linker", ["005", "002"], "IMPLEMENTED"),
        ("007", "Supervision verdict type (pass/fail/needs-review)", ["006"], "IMPLEMENTED"),
        ("008", "Verdict attached to TurnFinished", ["007"], "IMPLEMENTED"),
        ("009", "unexecuted-tests detector", ["006"], "IMPLEMENTED"),
        ("010", "unexecuted-build detector", ["006"], "IMPLEMENTED"),
        ("011", "ignored-failure detector", ["006"], "IMPLEMENTED"),
        ("012", "fake-completion detector", ["006"], "IMPLEMENTED"),
        ("013", "premature-stop detector (checklist coverage)", ["006"], "IMPLEMENTED"),
        ("014", "placeholder-code detector (diff scan)", ["004"], "IMPLEMENTED"),
        ("015", "mock-in-prod detector", ["004"], "IMPLEMENTED"),
        ("016", "requirement-skew detector", ["004"], "PLANNED"),
        ("017", "User appeal/override flow (journaled)", ["007"], "IMPLEMENTED"),
        ("018", "Evidence badges in conversation view", ["ui-040"], "IMPLEMENTED"),
        ("019", "Evidence drill-down viewer", ["018"], "PLANNED"),
        ("020", "Scripted dishonest-agent integration test", ["009", "010"], "PLANNED"),
        ("021", "Benchmark evidence recorder", ["001"], "PLANNED"),
        ("022", "Regression-test linkage recorder", ["001"], "PLANNED"),
        ("023", "EvidenceRecorded event + journal kind", ["001", "jour-023"], "PLANNED"),
        ("024", "Verdict override persistence across restarts", ["017", "jour-005"], "PLANNED"),
        ("025", "Supervision false-positive rate measurement harness", ["012"], "PLANNED"),
    ]),
    ("tok", "Token Economy & Caching", [
        ("001", "Prompt-prefix stability guard test (byte-exact)", [], "PLANNED"),
        ("002", "Prefix change impact documentation", ["001"], "PLANNED"),
        ("003", "Tool-result cache structure (fingerprint keys)", [], "IMPLEMENTED"),
        ("004", "Cache hit path end-to-end test", ["003"], "IMPLEMENTED"),
        ("005", "Cache invalidation on input fingerprint mismatch", ["003"], "IMPLEMENTED"),
        ("006", "Lazy tool advertisement (categories)", [], "PLANNED"),
        ("007", "On-demand full schema fetch tool", ["006"], "PLANNED"),
        ("008", "Structured large-output summaries w/ pointers", [], "PLANNED"),
        ("009", "Pinned-facts rule in summaries", ["008"], "PLANNED"),
        ("010", "Usage extraction: OpenAI include_usage", [], "PLANNED"),
        ("011", "Usage extraction: Anthropic usage fields", [], "PLANNED"),
        ("012", "UsageReported event + aggregates", ["010", "011"], "PLANNED"),
        ("013", "Estimator calibration loop (>15% drift trigger)", ["012"], "PLANNED"),
        ("014", "Calibration report artifact", ["013"], "PLANNED"),
        ("015", "Usage dashboard panel", ["012", "ui-050"], "PLANNED"),
        ("016", "Cost estimation from user-editable pricing table", ["015"], "PLANNED"),
        ("017", "cache_hit_rate metric", ["012"], "PLANNED"),
        ("018", "Context delta protocol research", [], "RESEARCH"),
        ("019", "Token-per-task accounting in orchestrator", ["012", "orch-004"], "PLANNED"),
        ("020", "Redundant-read detection (same file twice)", ["003"], "IMPLEMENTED"),
        ("021", "Repo-map cache keyed by input fingerprints", ["003"], "PLANNED"),
        ("022", "Estimator accuracy benchmark suite", ["013"], "PLANNED"),
        ("023", "Summary quality regression fixtures", ["009"], "PLANNED"),
        ("024", "Don't-send ladder audit checklist tooling", [], "PLANNED"),
        ("025", "Token waste report (weekly digest)", ["012"], "PLANNED"),
    ]),
    ("mem", "Memory Architecture", [
        ("001", "Memory record schema + store layout", [], "IMPLEMENTED"),
        ("002", "Layer stores (project/semantic/episodic)", ["001"], "IMPLEMENTED"),
        ("003", "Provenance + confidence fields enforced", ["001"], "IMPLEMENTED"),
        ("004", "Superseding chain support", ["001"], "IMPLEMENTED"),
        ("005", "Candidate extraction from journaled turns", ["001", "jour-005"], "IMPLEMENTED"),
        ("006", "Consolidation pass (batched, capped)", ["005"], "IMPLEMENTED"),
        ("007", "Provisional→promoted lifecycle", ["006"], "IMPLEMENTED"),
        ("008", "Retrieval API (ranked candidates)", ["002"], "IMPLEMENTED"),
        ("009", "Context injection respecting budgets", ["008", "ctx-001"], "IMPLEMENTED"),
        ("010", "User correction creates superseding record", ["004"], "IMPLEMENTED"),
        ("011", "Dependents flagged on correction", ["010"], "IMPLEMENTED"),
        ("012", "Memory inspector panel", ["ui-060"], "PLANNED"),
        ("013", "Recency decay in confidence scoring", ["006"], "IMPLEMENTED"),
        ("014", "Daily write cap enforcement", ["006"], "IMPLEMENTED"),
        ("015", "Memory replay from journal", ["005", "jour-005"], "PLANNED"),
        ("016", "Embedding-store choice ADR", [], "RESEARCH"),
        ("017", "Semantic retrieval layer (if justified)", ["016"], "RESEARCH"),
        ("018", "Anchor-based invalidation (file fingerprints)", ["001", "edit-001"], "PLANNED"),
        ("019", "Memory export/import", ["001", "exp-001"], "PLANNED"),
        ("020", "Consolidation bounds tests (caps honored)", ["006", "014"], "PLANNED"),
    ]),
    ("ctx", "Context Engine", [
        ("001", "Layered context model (prefix/session/turn/ephemeral)", [], "IMPLEMENTED"),
        ("002", "Priority allocation weights", ["001"], "IMPLEMENTED"),
        ("003", "Compaction trigger integration", ["001"], "IMPLEMENTED"),
        ("004", "Compaction procedure (pinned facts + round summaries)", ["003"], "PLANNED"),
        ("005", "Idempotent compaction per span", ["004"], "PLANNED"),
        ("006", "Freshness metadata on context items", ["001"], "PLANNED"),
        ("007", "Exact-source rehydration before edits", ["001", "edit-002"], "IMPLEMENTED"),
        ("008", "Context inspector panel data export", ["001", "ui-070"], "PLANNED"),
        ("009", "Priority weight settings (dev mode)", ["002", "set-002"], "PLANNED"),
        ("010", "Compaction journaling with token counts", ["004", "jour-001"], "PLANNED"),
        ("011", "Never-compact latest user message invariant test", ["004"], "PLANNED"),
        ("012", "Budget allocation unit tests", ["002"], "PLANNED"),
        ("013", "Freshness staleness warnings", ["006"], "PLANNED"),
        ("014", "Session layer persistence across restarts", ["001"], "PLANNED"),
        ("015", "Ephemeral layer lifetime management", ["001"], "PLANNED"),
    ]),
    ("prov", "Providers & Router", [
        ("001", "Retry/backoff policy module", ["core-016"], "PLANNED"),
        ("002", "Provider health check probe", [], "PLANNED"),
        ("003", "Connection reuse tuning benchmarks", [], "PLANNED"),
        ("004", "Model capability registry", [], "IMPLEMENTED"),
        ("005", "Router policy DSL parser", ["004"], "PLANNED"),
        ("006", "Router decision logging (reason per call)", ["005"], "IMPLEMENTED"),
        ("007", "Fallback chain evaluation", ["005"], "PLANNED"),
        ("008", "Hard-requirement bypass for downgrades", ["007"], "PLANNED"),
        ("009", "Router settings UI (dev mode)", ["005", "set-002"], "PLANNED"),
        ("010", "Provider SSE line-limit hardening", [], "PLANNED"),
        ("011", "Response size caps", ["010"], "PLANNED"),
        ("012", "Provider replay harness (recorded SSE fixtures)", ["fix-005"], "PLANNED"),
        ("013", "OpenAI replay fixture set", ["012"], "PLANNED"),
        ("014", "Anthropic replay fixture set", ["012"], "PLANNED"),
        ("015", "Contract test per provider against replays", ["013", "014"], "PLANNED"),
        ("016", "Local backend trait alignment study", [], "RESEARCH"),
        ("017", "llama.cpp server process manager", ["016"], "PLANNED"),
        ("018", "Local model catalog manifest format", ["017"], "PLANNED"),
        ("019", "Download manager with hash verification", ["018"], "PLANNED"),
        ("020", "Disk-space preflight checks", ["019"], "PLANNED"),
        ("021", "Local provider behind Provider trait", ["017"], "PLANNED"),
        ("022", "VRAM/RAM requirement declarations", ["021", "hw-001"], "PLANNED"),
        ("023", "Offline mode detection", ["021"], "PLANNED"),
        ("024", "Router E2E: failover transparent continuation", ["007", "015"], "PLANNED"),
        ("025", "Provider error sanitization audit (no creds)", ["015"], "PLANNED"),
    ]),
    ("hw", "Hardware Intelligence & Scheduler", [
        ("001", "Hardware probe service (CPU/RAM/GPU/VRAM)", [], "PLANNED"),
        ("002", "Thermal reading where available", ["001"], "PLANNED"),
        ("003", "Snapshot + change events API", ["001"], "PLANNED"),
        ("004", "Scheduler priority classes", [], "PLANNED"),
        ("005", "Admission control for background classes", ["004"], "PLANNED"),
        ("006", "Interactive-latency guard", ["005"], "PLANNED"),
        ("007", "Token/time budgets per class", ["004"], "PLANNED"),
        ("008", "Scheduler fairness metrics export", ["004"], "PLANNED"),
        ("009", "Local-model sizing recommendation from probe", ["001", "prov-022"], "PLANNED"),
        ("010", "Indexing parallelism from CPU topology", ["001"], "PLANNED"),
        ("011", "Render quality tiers from GPU class", ["001"], "PLANNED"),
        ("012", "Scheduler dashboard widgets", ["008", "ui-080"], "PLANNED"),
        ("013", "Admission-control stress test", ["005"], "PLANNED"),
        ("014", "Probe accuracy validation script", ["001"], "PLANNED"),
        ("015", "Battery-aware preset hooks", ["001"], "PLANNED"),
    ]),
    ("term", "Terminal Domain", [
        ("001", "PTY trait definition", [], "PLANNED"),
        ("002", "ConPTY backend", ["001"], "PLANNED"),
        ("003", "Unix openpty backend", ["001"], "PLANNED"),
        ("004", "Kill-on-close via job/group guards", ["002", "003"], "PLANNED"),
        ("005", "Ring buffer scrollback (10 MB cap)", ["001"], "PLANNED"),
        ("006", "VT sequence parser (vte-class)", ["005"], "PLANNED"),
        ("007", "Terminal panel renderer", ["006", "ui-090"], "PLANNED"),
        ("008", "Resize/reflow viewport-only", ["007"], "PLANNED"),
        ("009", "Scrollback search over raw bytes", ["005"], "PLANNED"),
        ("010", "Shell integration markers (OSC 133 wrapper)", [], "PLANNED"),
        ("011", "Marker heuristic fallback parsing", ["010"], "PLANNED"),
        ("012", "Multiple instances + split support", ["007"], "PLANNED"),
        ("013", "Agent supervised interactive sessions", ["001", "core-006"], "PLANNED"),
        ("014", "Per-line gated agent input", ["013"], "PLANNED"),
        ("015", "Detach/reattach support", ["013"], "PLANNED"),
        ("016", "Provenance badge for agent-launched runs", ["013"], "PLANNED"),
        ("017", "Terminal throughput benchmark", ["007"], "PLANNED"),
        ("018", "Unbounded-output memory safety test", ["005"], "PLANNED"),
        ("019", "Panel close kills tree test", ["004"], "PLANNED"),
        ("020", "Ctrl+` toggle wiring", ["007", "kb-001"], "PLANNED"),
    ]),
    ("ide", "IDE Surface", [
        ("001", "Buffer rope kernel", [], "PLANNED"),
        ("002", "Edit transactions with inverses", ["001"], "PLANNED"),
        ("003", "Undo grouping rules (500ms coalesce)", ["002"], "PLANNED"),
        ("004", "Agent-edit undo groups labeled", ["003"], "PLANNED"),
        ("005", "Undo depth 1000 + redo", ["003"], "PLANNED"),
        ("006", "Fingerprint tracking on commit", ["001", "edit-001"], "PLANNED"),
        ("007", "External-change conflict banner", ["006", "wat-001"], "PLANNED"),
        ("008", "Save routes through safe editing", ["006", "edit-004"], "PLANNED"),
        ("009", "tree-sitter highlight query sets", ["idx-004"], "PLANNED"),
        ("010", "Highlight theme token mapping", ["009", "theme-001"], "PLANNED"),
        ("011", "Editor v1 renderer (virtualized lines)", ["001", "ui-100"], "PLANNED"),
        ("012", "Large-file guard (>5MB read-only)", ["011"], "PLANNED"),
        ("013", "Go-to-def via index (F12)", ["idx-031", "kb-002"], "PLANNED"),
        ("014", "Find-references via index (Shift+F12)", ["idx-032", "kb-002"], "PLANNED"),
        ("015", "LSP client lifecycle (spawn/handshake/shutdown)", [], "PLANNED"),
        ("016", "LSP request multiplexing + id map", ["015"], "PLANNED"),
        ("017", "LSP crash restart w/ backoff (max 3)", ["015"], "PLANNED"),
        ("018", "Degraded mode (index-only nav)", ["017"], "PLANNED"),
        ("019", "Completion merge (LSP primary/index fallback)", ["016", "idx-014"], "PLANNED"),
        ("020", "Diagnostics publish → gutter + problems", ["016", "ui-110"], "PLANNED"),
        ("021", "Inline diff review of agent edits", ["edit-019", "diff-001"], "PLANNED"),
        ("022", "Minimap (later phase)", ["011"], "PLANNED"),
        ("023", "ropey dependency ADR", [], "RESEARCH"),
        ("024", "Editor keyboard map defaults", ["kb-002"], "PLANNED"),
        ("025", "Editor a11y (labels/roles/caret announcements)", ["011"], "PLANNED"),
    ]),
    ("diff", "Diff Viewer", [
        ("001", "Unified diff renderer", ["edit-019"], "PLANNED"),
        ("002", "Split view toggle", ["001"], "PLANNED"),
        ("003", "Syntax-aware highlighting in diffs", ["001", "ide-009"], "PLANNED"),
        ("004", "Hunk-level accept/reject", ["001", "edit-012"], "PLANNED"),
        ("005", "Virtualized huge-diff rendering", ["001"], "PLANNED"),
        ("006", "Binary/image diff placeholders", ["001", "edit-021"], "PLANNED"),
        ("007", "Word-wrap off default + toggle", ["001"], "PLANNED"),
        ("008", "Patch proposal review flow", ["004", "edit-008"], "PLANNED"),
        ("009", "Conflict surfacing (fingerprint mismatch)", ["004", "edit-003"], "PLANNED"),
        ("010", "Diff performance benchmark (10k-line diff)", ["005"], "PLANNED"),
    ]),
    ("brw", "Browser Domain", [
        ("001", "WebView surface trait (per-platform)", [], "PLANNED"),
        ("002", "WebView2 Windows backend", ["001"], "PLANNED"),
        ("003", "WebKitGTK Linux backend", ["001"], "PLANNED"),
        ("004", "WKWebView macOS backend", ["001"], "PLANNED"),
        ("005", "Instance pool management", ["001"], "PLANNED"),
        ("006", "Profile separation (user vs agent)", ["001"], "PLANNED"),
        ("007", "browser_open/read/act tools (risk-classified)", ["006"], "PLANNED"),
        ("008", "Readability extraction pipeline", ["007"], "PLANNED"),
        ("009", "Download quarantine + scan hook", ["001"], "PLANNED"),
        ("010", "Devtools toggle (dev mode)", ["001"], "PLANNED"),
        ("011", "Cookie isolation test (agent never sees user)", ["006"], "PLANNED"),
        ("012", "Privileged-bridge absence audit", ["001"], "PLANNED"),
        ("013", "Browser pane shell integration", ["001", "ui-120"], "PLANNED"),
        ("014", "Research session citation artifacts", ["008", "art-001"], "PLANNED"),
    ]),
    ("dia", "Diagram Engine", [
        ("001", "Mermaid-class subset parser", [], "PLANNED"),
        ("002", "Graph model (nodes/edges/subgraphs)", ["001"], "PLANNED"),
        ("003", "Cycle removal pass", ["002"], "PLANNED"),
        ("004", "Layering pass", ["003"], "PLANNED"),
        ("005", "Ordering pass", ["004"], "PLANNED"),
        ("006", "Coordinate assignment", ["005"], "PLANNED"),
        ("007", "Scene primitive rendering", ["006", "ui-130"], "PLANNED"),
        ("008", "Flowchart TD/LR support", ["007"], "PLANNED"),
        ("009", "Sequence diagram support", ["007"], "PLANNED"),
        ("010", "Class diagram basic support", ["007"], "PLANNED"),
        ("011", "Unsupported-construct honest node", ["001"], "PLANNED"),
        ("012", "Pan/zoom view state", ["007"], "PLANNED"),
        ("013", "Node selection → symbol navigation", ["007", "idx-031"], "PLANNED"),
        ("014", "PNG/SVG export via offscreen capture", ["007"], "PLANNED"),
        ("015", "Dependency-graph generation from index", ["idx-034", "002"], "PLANNED"),
        ("016", "diagram_render tool (ReadOnly)", ["008"], "PLANNED"),
    ]),
    ("db", "Database Workspace", [
        ("001", "Connection registry + secret-store refs", [], "PLANNED"),
        ("002", "rusqlite driver integration", ["001"], "PLANNED"),
        ("003", "Postgres pure-Rust client evaluation", [], "RESEARCH"),
        ("004", "Schema tree fetch + fingerprint cache", ["002"], "PLANNED"),
        ("005", "Statement classifier (read/write/DDL)", ["002"], "PLANNED"),
        ("006", "Read-only default sessions", ["005"], "PLANNED"),
        ("007", "Write approval per statement", ["005"], "PLANNED"),
        ("008", "DDL typed confirmation", ["005"], "PLANNED"),
        ("009", "Results grid virtualized", ["002", "ui-140"], "PLANNED"),
        ("010", "Row cursor streaming", ["009"], "PLANNED"),
        ("011", "Large-cell truncation + fetch-on-demand", ["010"], "PLANNED"),
        ("012", "Query cancel mapping per driver", ["010"], "PLANNED"),
        ("013", "Query history journaling", ["010", "jour-001"], "PLANNED"),
        ("014", "Export CSV/JSONL", ["010"], "PLANNED"),
        ("015", "Schema-aware completion", ["004"], "PLANNED"),
        ("016", "db_schema/db_query/db_execute tools", ["005"], "PLANNED"),
        ("017", "Connection pool health checks", ["001"], "PLANNED"),
        ("018", "Credential never-cached-beyond-session test", ["001"], "PLANNED"),
    ]),
    ("api", "API Workbench", [
        ("001", "Request model (method/url/headers/body/auth refs)", [], "PLANNED"),
        ("002", "Environment variable scopes", ["001"], "PLANNED"),
        ("003", "Collections as workspace files", ["001"], "PLANNED"),
        ("004", "Execution via shared HTTP stack", ["001"], "PLANNED"),
        ("005", "Response inspector (pretty/raw/headers)", ["004"], "PLANNED"),
        ("006", "Size caps + binary detection", ["005"], "PLANNED"),
        ("007", "Request history", ["004"], "PLANNED"),
        ("008", "http_request tool (Execute risk)", ["004"], "PLANNED"),
        ("009", "OpenAPI spec import", ["001"], "PLANNED"),
        ("010", "Agent request drafting assistance", ["009"], "PLANNED"),
        ("011", "Send approval gate", ["008"], "PLANNED"),
        ("012", "Egress policy hook", ["008"], "PLANNED"),
        ("013", "API workbench panel", ["005", "ui-150"], "PLANNED"),
        ("014", "Streaming body support research", [], "RESEARCH"),
    ]),
    ("data", "Data Workspace", [
        ("001", "CSV streaming reader + dialect sniffing", [], "PLANNED"),
        ("002", "JSONL reader", ["001"], "PLANNED"),
        ("003", "Parquet reader evaluation", [], "RESEARCH"),
        ("004", "Virtualized table view", ["001", "ui-160"], "PLANNED"),
        ("005", "Column profiling (lazy)", ["004"], "PLANNED"),
        ("006", "Transform recipe steps (declarative)", ["004"], "PLANNED"),
        ("007", "Recipe journaling + reproducibility", ["006", "jour-001"], "PLANNED"),
        ("008", "Recipe export as scripts", ["007"], "PLANNED"),
        ("009", "Simple plots (categorical/numeric)", ["005"], "PLANNED"),
        ("010", "Large-file pagination", ["004"], "PLANNED"),
    ]),
    ("auto", "Automation Engine", [
        ("001", "Trigger types (cron/watch/manual/app-event)", ["wf-001"], "PLANNED"),
        ("002", "Local cron scheduler", ["001"], "PLANNED"),
        ("003", "Missed-fire resolve-once-on-wake", ["002"], "PLANNED"),
        ("004", "File-watch triggers (debounced)", ["001", "wat-001"], "PLANNED"),
        ("005", "Runs as journaled tasks with budgets", ["001", "orch-001"], "PLANNED"),
        ("006", "Global + per-trigger concurrency caps", ["005"], "PLANNED"),
        ("007", "Quiet hours respect", ["002"], "PLANNED"),
        ("008", "Automation settings UI", ["001", "set-002"], "PLANNED"),
        ("009", "Automation run history view", ["005", "ui-170"], "PLANNED"),
        ("010", "Stampede prevention tests", ["003"], "PLANNED"),
    ]),
    ("wf", "Workflow Engine", [
        ("001", "Workflow file format (versioned steps)", [], "PLANNED"),
        ("002", "Step executor (prompts/tools/approvals/gates)", ["001"], "PLANNED"),
        ("003", "Gate types (approval/evidence/budget/verdict)", ["002"], "PLANNED"),
        ("004", "Failure policies (retry/skip/abort/ask)", ["002"], "PLANNED"),
        ("005", "Run instantiation as tasks", ["002", "orch-001"], "PLANNED"),
        ("006", "workflow_start/status tools", ["005"], "PLANNED"),
        ("007", "Workflow versioning + migration", ["001"], "PLANNED"),
        ("008", "Example workflows shipped (templates)", ["002"], "PLANNED"),
        ("009", "Workflow run E2E test", ["005"], "PLANNED"),
        ("010", "Gate bypass prevention tests", ["003"], "PLANNED"),
    ]),
    ("art", "Artifact Platform", [
        ("001", "Content-addressed blob store", [], "PLANNED"),
        ("002", "Manifest index.jsonl records", ["001"], "PLANNED"),
        ("003", "Version chains (version_of)", ["002"], "PLANNED"),
        ("004", "Preview renderers (markdown/text/image)", ["002"], "PLANNED"),
        ("005", "Diagram/patch preview renderers", ["004", "dia-007"], "PLANNED"),
        ("006", "Gallery panel", ["004", "ui-180"], "PLANNED"),
        ("007", "artifact_save/list tools", ["002"], "PLANNED"),
        ("008", "Export to chosen location", ["001"], "PLANNED"),
        ("009", "Provenance linking (turn/task)", ["002"], "PLANNED"),
        ("010", "Screenshot artifacts from --shot", ["004"], "PLANNED"),
    ]),
    ("sec", "Security Hardening", [
        ("001", "DPAPI secret store (Windows)", [], "PLANNED"),
        ("002", "Config migration: key → secrets store", ["001"], "PLANNED"),
        ("003", "Secret-blob scan gating (logs/journals)", ["001"], "PLANNED"),
        ("004", "Export excludes secrets by default", ["001"], "PLANNED"),
        ("005", "Corrupt-blob clear-error path", ["001"], "PLANNED"),
        ("006", "keyring crate evaluation for unix/mac", [], "RESEARCH"),
        ("007", "Redaction applied to log sink", ["red-002"], "PLANNED"),
        ("008", "Redaction applied to journal", ["red-002", "jour-015"], "PLANNED"),
        ("009", "Egress audit: no unexpected outbound calls", [], "PLANNED"),
        ("010", "MCP client behind Risk machinery", ["mcp-001"], "PLANNED"),
        ("011", "Extension permission system (deny-by-default)", ["ext-001"], "PLANNED"),
        ("012", "Permission revocation UI", ["011"], "PLANNED"),
        ("013", "Declared-vs-used capability check", ["011"], "PLANNED"),
        ("014", "Network egress policy for extensions", ["011"], "PLANNED"),
        ("015", "Destructive-op confirmation framework", [], "PLANNED"),
        ("016", "Delete-class tool confirmations", ["015"], "PLANNED"),
        ("017", "Force-git-op prohibition tests", ["edit-028"], "PLANNED"),
        ("018", "cargo-deny license gate", [], "PLANNED"),
        ("019", "Dependency security advisory monitoring plan", ["018"], "PLANNED"),
        ("020", "Extension signing design", ["ext-001"], "RESEARCH"),
    ]),
    ("red", "Redaction Expansion", [
        ("001", "Rule coverage review (new provider formats)", [], "PLANNED"),
        ("002", "Central redaction funnel for all sinks", ["001"], "PLANNED"),
        ("003", "Log sink integration", ["002"], "PLANNED"),
        ("004", "Journal integration", ["002"], "PLANNED"),
        ("005", "Scan-based zero-leak test suite", ["003", "004"], "PLANNED"),
        ("006", "Performance benchmark (1MB <20ms)", ["002"], "PLANNED"),
        ("007", "Custom rule configuration (dev mode)", ["001", "set-002"], "PLANNED"),
    ]),
    ("mcp", "MCP Integration", [
        ("001", "MCP client core (stdio transport)", [], "PLANNED"),
        ("002", "Server process sandboxing", ["001"], "PLANNED"),
        ("003", "Tool exposure through ToolDef registry", ["001"], "PLANNED"),
        ("004", "Provenance tagging (via mcp:<server>)", ["003"], "PLANNED"),
        ("005", "Resource mapping into context engine", ["001", "ctx-001"], "PLANNED"),
        ("006", "Per-server permissions deny-by-default", ["001"], "PLANNED"),
        ("007", "Server crash containment", ["002"], "PLANNED"),
        ("008", "MCP conformance test server fixture", ["003"], "PLANNED"),
        ("009", "HTTP transport evaluation", [], "RESEARCH"),
        ("010", "MCP settings UI (servers list)", ["006", "set-002"], "PLANNED"),
    ]),
    ("ext", "Extensions / Plugin SDK", [
        ("001", "Extension manifest format (TOML/JSON)", [], "PLANNED"),
        ("002", "In-process trait contracts v1", ["001"], "PLANNED"),
        ("003", "Tool extension kind", ["002"], "PLANNED"),
        ("004", "Provider extension kind", ["002"], "PLANNED"),
        ("005", "Parser extension kind", ["002"], "PLANNED"),
        ("006", "Panel extension kind", ["002"], "PLANNED"),
        ("007", "Renderer extension kind", ["002"], "PLANNED"),
        ("008", "Command extension kind", ["002"], "PLANNED"),
        ("009", "Panic-hook containment v1", ["002"], "PLANNED"),
        ("010", "Version-compatible load checking", ["001"], "PLANNED"),
        ("011", "Conformance suites per kind", ["003", "004", "005", "006", "007", "008"], "PLANNED"),
        ("012", "Out-of-process host design", ["002"], "RESEARCH"),
        ("013", "SDK docs + example extensions", ["011"], "PLANNED"),
        ("014", "Built-ins dogfood extension API", ["011"], "PLANNED"),
    ]),
    ("set", "Settings System", [
        ("001", "SettingDef schema representation", [], "IMPLEMENTED"),
        ("002", "Initial schema population (§75 draft)", ["001"], "PLANNED"),
        ("003", "Typed accessor cache", ["001"], "IMPLEMENTED"),
        ("004", "SetSetting command + change events", ["003"], "IMPLEMENTED"),
        ("005", "Validation + constraint reset-with-warning", ["001"], "PLANNED"),
        ("006", "Unknown-key keep+warn behavior", ["005"], "PLANNED"),
        ("007", "Migration framework (versioned files)", ["001"], "PLANNED"),
        ("008", "Search index over schema", ["002"], "PLANNED"),
        ("009", "Settings pages UI (schema-rendered)", ["004", "ui-190"], "PLANNED"),
        ("010", "User/Developer mode visibility filter", ["009"], "PLANNED"),
        ("011", "Presets (named bundles)", ["004"], "PLANNED"),
        ("012", "Reset-to-default round trip test", ["005"], "PLANNED"),
        ("013", "Migration tests (v(n)→v(n+1))", ["007"], "PLANNED"),
        ("014", "Secrets exclusion enforcement", ["004", "sec-004"], "PLANNED"),
        ("015", "Workspace profile overrides (.zdesktop)", ["004"], "PLANNED"),
    ]),
    ("theme", "Theme System", [
        ("001", "Semantic token catalog finalization (§76)", [], "PLANNED"),
        ("002", "z-dark theme passes contrast gates", ["001"], "PLANNED"),
        ("003", "z-light theme", ["002"], "PLANNED"),
        ("004", "High-contrast theme (AAA text)", ["003"], "PLANNED"),
        ("005", "Theme file versioning + unknown-token warn", ["001"], "PLANNED"),
        ("006", "Theme editor UI (live preview)", ["005", "ui-200"], "PLANNED"),
        ("007", "Import/export single files", ["005"], "PLANNED"),
        ("008", "Syntax palette family tokens", ["001"], "PLANNED"),
        ("009", "Terminal ANSI family tokens", ["001"], "PLANNED"),
        ("010", "Chart categorical family", ["001"], "PLANNED"),
        ("011", "Hardcoded-color lint (CI grep gate)", ["001"], "PLANNED"),
        ("012", "Reduced-motion global honor", ["001"], "PLANNED"),
    ]),
    ("layout", "Dock & Layout", [
        ("001", "Region tree operations (pure)", [], "PLANNED"),
        ("002", "Drag-to-dock with drop indicators", ["001"], "PLANNED"),
        ("003", "Escape cancels drag", ["002"], "PLANNED"),
        ("004", "Keyboard splitter adjustment", ["001"], "PLANNED"),
        ("005", "Min-size rebalancing", ["001"], "PLANNED"),
        ("006", "Layout undo stack (depth 50)", ["001"], "PLANNED"),
        ("007", "Presets switcher", ["001"], "PLANNED"),
        ("008", "Per-workspace persistence", ["007", "set-015"], "PLANNED"),
        ("009", "Layout serialization migrations", ["008"], "PLANNED"),
        ("010", "Floating panels (later)", ["002"], "PLANNED"),
        ("011", "Layout constraint tests (sum≈1, min sizes)", ["005"], "PLANNED"),
        ("012", "Empty-state focus when last panel closes", ["001"], "PLANNED"),
    ]),
    ("kb", "Keybindings", [
        ("001", "Keymap tables as data in z-shell", [], "PLANNED"),
        ("002", "Default bindings population (§81)", ["001"], "PLANNED"),
        ("003", "Remap UI", ["002", "set-009"], "PLANNED"),
        ("004", "Chord support", ["001"], "PLANNED"),
        ("005", "Scope-specificity conflict resolution", ["001"], "PLANNED"),
        ("006", "Binding export/import", ["003"], "PLANNED"),
    ]),
    ("a11y", "Accessibility Audit", [
        ("001", "accesskit node coverage audit tooling", [], "PLANNED"),
        ("002", "Conversation view audit", ["001"], "PLANNED"),
        ("003", "Terminal audit", ["001", "term-007"], "PLANNED"),
        ("004", "Editor audit", ["001", "ide-025"], "PLANNED"),
        ("005", "Focus-order visual-order test", ["001"], "PLANNED"),
        ("006", "Screen-reader streaming announcements (throttled)", ["001"], "PLANNED"),
        ("007", "Modal trap/restore tests", ["001"], "PLANNED"),
        ("008", "Contrast gate automation for themes", ["theme-002"], "PLANNED"),
        ("009", "Keyboard-only walkthrough scripts", ["001"], "PLANNED"),
        ("010", "A11y regression gates in CI", ["002", "003", "004"], "PLANNED"),
    ]),
    ("diag", "Diagnostics & Observability", [
        ("001", "Rotating file log sink", [], "PLANNED"),
        ("002", "Metrics counters/histograms facade", [], "PLANNED"),
        ("003", "Local JSONL metrics export", ["002"], "PLANNED"),
        ("004", "Trace span export (turn-scoped)", ["core-032"], "PLANNED"),
        ("005", "Diagnostics console panel", ["003", "ui-210"], "PLANNED"),
        ("006", "Crash dump + journal-tail capture", [], "PLANNED"),
        ("007", "Metric definitions doc sync checker", ["002"], "PLANNED"),
        ("008", "Frame-time instrumentation dashboards", ["002", "gpui-002"], "PLANNED"),
        ("009", "Log level runtime control (dev mode)", ["001", "set-002"], "PLANNED"),
        ("010", "Zero-telemetry egress test", ["sec-009"], "PLANNED"),
    ]),
    ("perf", "Performance Benchmarks", [
        ("001", "Benchmark harness scaffold + docs/benchmarks/", [], "PLANNED"),
        ("002", "Scene build <2ms benchmark", ["001"], "PLANNED"),
        ("003", "Input echo <16ms benchmark", ["001"], "PLANNED"),
        ("004", "Panel switch <50ms benchmark", ["001"], "PLANNED"),
        ("005", "Cold start <1.5s benchmark", ["001"], "PLANNED"),
        ("006", "Idle CPU ~0% verification", ["001"], "PLANNED"),
        ("007", "Idle RAM <150MB verification", ["001"], "PLANNED"),
        ("008", "Redaction 1MB <20ms benchmark", ["001"], "PLANNED"),
        ("009", "Sandbox spawn→resume <30ms benchmark", ["001"], "PLANNED"),
        ("010", "Regression gate CI job (>20% fails)", ["002", "003", "004"], "PLANNED"),
    ]),
    ("ci", "CI & Release Engineering", [
        ("001", "GitHub Actions workflow scaffold", [], "PLANNED"),
        ("002", "Test job (windows/ubuntu/macos matrix)", ["001"], "PLANNED"),
        ("003", "Clippy/fmt gates", ["001"], "PLANNED"),
        ("004", "Security scan job", ["001"], "PLANNED"),
        ("005", "Release build job (tag-triggered)", ["001"], "PLANNED"),
        ("006", "Artifact upload + checksums", ["005"], "PLANNED"),
        ("007", "Changelog generation from ledger", ["005"], "PLANNED"),
        ("008", "rust-toolchain pinning", ["005"], "PLANNED"),
        ("009", "ARM64 runner inclusion", ["002"], "PLANNED"),
        ("010", "Release smoke-run script", ["006"], "PLANNED"),
    ]),
    ("xp", "Cross-Platform Parity", [
        ("001", "Linux build fixes (first pass)", [], "PLANNED"),
        ("002", "macOS build fixes (first pass)", [], "PLANNED"),
        ("003", "Path handling audit (separators/case)", [], "PLANNED"),
        ("004", "Shell construction per-platform tests", [], "PLANNED"),
        ("005", "Line-ending normalization boundaries", [], "PLANNED"),
        ("006", "Parity tracker in ledger (per feature)", [], "PLANNED"),
        ("007", "Linux CI green", ["ci-002", "001"], "PLANNED"),
        ("008", "macOS CI green", ["ci-002", "002"], "PLANNED"),
        ("009", "ARM64 Windows smoke test", ["ci-009"], "PLANNED"),
        ("010", "Platform-specific code isolation audit", [], "PLANNED"),
    ]),
    ("wat", "Watcher Service", [
        ("001", "notify-based watcher service", [], "PLANNED"),
        ("002", "Debounce 300ms + burst coalescing", ["001"], "PLANNED"),
        ("003", "Refcounted subscriptions", ["001"], "PLANNED"),
        ("004", "Overflow → subtree rescan", ["001"], "PLANNED"),
        ("005", "Watcher death restart w/ backoff", ["001"], "PLANNED"),
        ("006", "Sequence-numbered batches", ["002"], "PLANNED"),
        ("007", "Ignore patterns shared with walk_files", ["001"], "PLANNED"),
        ("008", "Watcher integration tests (temp dirs)", ["001"], "PLANNED"),
    ]),
    ("prev", "Live Preview", [
        ("001", "Loopback static server", [], "PLANNED"),
        ("002", "Traversal-guarded root serving", ["001"], "PLANNED"),
        ("003", "EventSource reload injection", ["001", "wat-001"], "PLANNED"),
        ("004", "Scroll preservation across reloads", ["003"], "PLANNED"),
        ("005", "Preview pane shell integration", ["001", "ui-220"], "PLANNED"),
        ("006", "--shot of preview URL for agents", ["005"], "PLANNED"),
        ("007", "Port binding config (ephemeral default)", ["001"], "PLANNED"),
    ]),
    ("srch", "Search & Research", [
        ("001", "Web search provider abstraction", [], "PLANNED"),
        ("002", "Result provenance attachment", ["001"], "PLANNED"),
        ("003", "Research session container", ["002"], "PLANNED"),
        ("004", "Cited-artifact output", ["003", "art-001"], "PLANNED"),
        ("005", "Local corpus search integration", ["idx-020"], "PLANNED"),
        ("006", "search_p95 metric", ["005"], "PLANNED"),
    ]),
    ("exp", "Export/Import", [
        ("001", "Export bundle format + version header", [], "PLANNED"),
        ("002", "Threads export (bundle/per-file)", ["001"], "PLANNED"),
        ("003", "Settings export (secrets excluded)", ["001", "sec-004"], "PLANNED"),
        ("004", "Import validation + explicit conflict resolution", ["001"], "PLANNED"),
        ("005", "Secret-import typed confirmation + journaling", ["004"], "PLANNED"),
        ("006", "Round-trip tests (export→import equality)", ["002", "003"], "PLANNED"),
    ]),
    ("upd", "Updates", [
        ("001", "Manual update-check action", [], "PLANNED"),
        ("002", "GitHub release metadata fetch", ["001"], "PLANNED"),
        ("003", "Semver-aware comparison incl. pre-releases", ["002"], "PLANNED"),
        ("004", "Release notes in-app rendering", ["002"], "PLANNED"),
        ("005", "Quiet network-failure handling", ["002"], "PLANNED"),
    ]),
    ("notif", "Notifications", [
        ("001", "Notification shell state model", [], "PLANNED"),
        ("002", "Quiet-by-default behavior (badge only)", ["001"], "PLANNED"),
        ("003", "Error persistence + others expire", ["001"], "PLANNED"),
        ("004", "Action buttons mapped to commands", ["001"], "PLANNED"),
        ("005", "Cap 50 + pruning", ["001"], "PLANNED"),
    ]),
    ("pal", "Command Palette", [
        ("001", "Action registry", [], "PLANNED"),
        ("002", "Fuzzy matcher (subsequence+bonus)", ["001"], "PLANNED"),
        ("003", "Recency boost", ["002"], "PLANNED"),
        ("004", "Palette UI", ["002", "ui-230"], "PLANNED"),
        ("005", "Settings/keybinding auto-indexing", ["001", "set-008"], "PLANNED"),
        ("006", "Extension action registration", ["001", "ext-008"], "PLANNED"),
    ]),
    ("quick", "Quick Open", [
        ("001", "Fuzzy file/thread/symbol switcher", ["idx-020"], "PLANNED"),
        ("002", "Recent-first empty-query behavior", ["001"], "PLANNED"),
        ("003", "Directory-boundary scoring", ["001"], "PLANNED"),
        ("004", "Split-open modifier", ["001"], "PLANNED"),
    ]),
    ("ftree", "File Tree Panel", [
        ("001", "Lazy directory nodes", [], "PLANNED"),
        ("002", "Git status overlay (incremental)", ["001", "wat-001"], "PLANNED"),
        ("003", "Type-ahead filtered flat view", ["001"], "PLANNED"),
        ("004", "Keyboard navigation + rename/delete", ["001", "edit-026"], "PLANNED"),
        ("005", ">1000-entry pagination", ["001"], "PLANNED"),
        ("006", "Visible-page stat batching", ["001"], "PLANNED"),
    ]),
    ("prob", "Problems Panel", [
        ("001", "Unified item model", [], "PLANNED"),
        ("002", "Source integrations (LSP/build/supervision/sandbox)", ["001"], "PLANNED"),
        ("003", "Click-through navigation/evidence", ["002"], "PLANNED"),
        ("004", "Filters + quiet badges", ["001"], "PLANNED"),
    ]),
    ("srep", "Search & Replace Across Files", [
        ("001", "Search panel (regex/globs/scope)", ["idx-020"], "PLANNED"),
        ("002", "Grouped results with context", ["001"], "PLANNED"),
        ("003", "Staged replace preview", ["002", "edit-008"], "PLANNED"),
        ("004", "Apply-all via safe editing", ["003"], "PLANNED"),
        ("005", "Individual failure listing", ["004"], "PLANNED"),
        ("006", "Undo-as-one-group", ["004", "ide-004"], "PLANNED"),
    ]),
    ("threads", "Thread Management", [
        ("001", "Thread list panel", ["core-021"], "PLANNED"),
        ("002", "Operations (new/open/rename/delete/duplicate)", ["001", "core-022"], "PLANNED"),
        ("003", "Recency sort + content-prefix search", ["001"], "PLANNED"),
        ("004", "Restore-most-recent on startup", ["001", "core-025"], "PLANNED"),
    ]),
    ("ui", "UI Shell Surfaces", [
        ("010", "Conversation view upgrades (steering indicator)", ["core-005"], "PLANNED"),
        ("020", "Component library: button/input/list/tabs/dialog", [], "PLANNED"),
        ("021", "Component library: tooltip/badge/empty/skeleton/toast", ["020"], "PLANNED"),
        ("022", "Component library: splitter", ["020"], "PLANNED"),
        ("030", "Sidebar panel scaffold", ["020"], "IMPLEMENTED"),
        ("040", "Evidence badge components", ["020", "sup-018"], "IMPLEMENTED"),
        ("050", "Usage dashboard panel", ["020", "tok-015"], "PLANNED"),
        ("060", "Memory inspector panel", ["020", "mem-012"], "PLANNED"),
        ("070", "Context inspector panel", ["020", "ctx-008"], "PLANNED"),
        ("080", "Scheduler dashboard widgets", ["020", "hw-012"], "PLANNED"),
        ("090", "Terminal panel host", ["020", "term-007"], "PLANNED"),
        ("100", "Editor panel host", ["020", "ide-011"], "PLANNED"),
        ("110", "Problems panel host", ["020", "prob-002"], "PLANNED"),
        ("120", "Browser pane host", ["020", "brw-013"], "PLANNED"),
        ("130", "Diagram canvas host", ["020", "dia-007"], "PLANNED"),
        ("140", "DB grid host", ["020", "db-009"], "PLANNED"),
        ("150", "API workbench host", ["020", "api-013"], "PLANNED"),
        ("160", "Data table host", ["020", "data-004"], "PLANNED"),
        ("170", "Automation history host", ["020", "auto-009"], "PLANNED"),
        ("180", "Artifact gallery host", ["020", "art-006"], "PLANNED"),
        ("190", "Settings pages host", ["020", "set-009"], "PLANNED"),
        ("200", "Theme editor host", ["020", "theme-006"], "PLANNED"),
        ("210", "Diagnostics console host", ["020", "diag-005"], "PLANNED"),
        ("220", "Preview pane host", ["020", "prev-005"], "PLANNED"),
        ("230", "Palette host", ["020", "pal-004"], "PLANNED"),
        ("240", "Notification center host", ["020", "notif-001"], "PLANNED"),
        ("250", "Diff viewer host", ["020", "diff-001"], "PLANNED"),
        ("260", "File tree host", ["020", "ftree-001"], "PLANNED"),
        ("270", "Thread list host", ["020", "threads-001"], "PLANNED"),
        ("280", "Search/replace host", ["020", "srep-001"], "PLANNED"),
        ("290", "Quick-open host", ["020", "quick-001"], "PLANNED"),
    ]),
    ("gpui", "Rendering Runtime", [
        ("001", "Device-loss recovery path", [], "PLANNED"),
        ("002", "Batching optimization pass", [], "PLANNED"),
        ("003", "Shaped-run cache tuning", [], "PLANNED"),
        ("004", "Frame-time regression gate", ["perf-002"], "PLANNED"),
        ("005", "Multi-window readiness (shell per-window)", [], "PLANNED"),
        ("006", "DPI correctness audit", [], "PLANNED"),
        ("007", "Animation token-driven durations", ["theme-001"], "PLANNED"),
        ("008", "Virtualization primitives (list/table/tree)", [], "PLANNED"),
        ("009", "Offscreen capture robustness", [], "PLANNED"),
        ("010", "wgpu backend matrix smoke tests", ["xp-001", "xp-002"], "PLANNED"),
    ]),
    ("shell", "Shell Model", [
        ("001", "View-state persistence across restarts", [], "PLANNED"),
        ("002", "Focus model hardening", [], "PLANNED"),
        ("003", "Streaming buffer memory caps", [], "PLANNED"),
        ("004", "Pending approvals mirror sync", [], "PLANNED"),
        ("005", "Corrupt-layout tolerant load", [], "PLANNED"),
        ("006", "Shell transition property tests", [], "PLANNED"),
    ]),
    ("docs", "Documentation & Canonicalization", [
        ("001", "ADR files created for ADR-0001..0006", [], "PLANNED"),
        ("002", "README final polish", [], "PLANNED"),
        ("003", "Spec cross-reference link checker", [], "PLANNED"),
        ("004", "Ledger validator in CI", ["ci-001"], "PLANNED"),
        ("005", "Onboarding guide review", [], "PLANNED"),
        ("006", "Glossary consolidation pass", [], "PLANNED"),
        ("007", "Research docs refresh cadence rule", [], "PLANNED"),
        ("008", "License decision ADR", [], "RESEARCH"),
    ]),
    ("fix", "Fixtures", [
        ("001", "tiny-repo fixture", [], "PLANNED"),
        ("002", "medium-repo generator (~200 files)", ["001"], "PLANNED"),
        ("003", "large-repo generator (~5k files)", ["002"], "PLANNED"),
        ("004", "xl-repo generator (~50k files)", ["003"], "PLANNED"),
        ("005", "provider SSE recording tool", [], "PLANNED"),
        ("006", "journal-seq scripted segments", [], "PLANNED"),
        ("007", "layout version fixtures v1..vN", [], "PLANNED"),
    ]),
    ("tests", "Test Suite Expansion", [
        ("001", "Protocol unknown-field tolerance tests", [], "PLANNED"),
        ("002", "Provider malformed-SSE failure tests", ["prov-012"], "PLANNED"),
        ("003", "Provider timeout failure tests", ["prov-012"], "PLANNED"),
        ("004", "Shell corrupt-layout tests", ["shell-005"], "PLANNED"),
        ("005", "GPUI device-loss tests", ["gpui-001"], "PLANNED"),
        ("006", "App pump backpressure tests", [], "PLANNED"),
        ("007", "Runtime provider-fail/retry tests", ["core-016"], "PLANNED"),
        ("008", "Soak test automation entry", ["core-030"], "PLANNED"),
        ("009", "Fuzz targets: scoped(), patch apply, protocol parse", [], "PLANNED"),
        ("010", "Fuzz CI integration", ["009", "ci-001"], "PLANNED"),
    ]),
]

def main():
    # Build id maps and validate deps
    ids = {}
    tasks = []
    for key, title, items in DOMAINS:
        for suffix, ttitle, deps, status in items:
            tid = f"{key}-{suffix}"
            if tid in ids:
                raise SystemExit(f"duplicate id {tid}")
            ids[tid] = True
            tasks.append((tid, key, title, ttitle, deps, status))
    # validate deps exist
    dep_errors = []
    for tid, key, _, _, deps, _ in tasks:
        for d in deps:
            dfull = d if "-" in d and d.split("-")[0] in dict((k, 1) for k, _, _ in DOMAINS) else f"{key}-{d}"
            if dfull not in ids:
                dep_errors.append(f"{tid} -> missing dep {dfull}")
    if dep_errors:
        raise SystemExit("dep errors:\n" + "\n".join(dep_errors))

    total = len(tasks)
    counts = {}
    for _, _, _, _, _, s in tasks:
        counts[s] = counts.get(s, 0) + 1

    lines = []
    lines.append("# Z Desktop — Engineering Task Ledger")
    lines.append("")
    lines.append("> **Canonical backlog**: every planned unit of engineering work.")
    lines.append("> **Status vocabulary**: IMPLEMENTED / PARTIAL / PLANNED / EXPERIMENTAL / RESEARCH (see Master Spec §7).")
    lines.append("> **Rules**: statuses change only with evidence; dependencies must be [x] before dependents start; this file is generated by `tools/gen_tasks.py` — edit the generator, not this file, for structural changes; per-task progress notes may be appended manually under each task.")
    lines.append("")
    lines.append(f"**Total tasks**: {total}")
    lines.append("")
    lines.append("| Status | Count |")
    lines.append("|---|---|")
    for s in ["IMPLEMENTED", "PARTIAL", "PLANNED", "EXPERIMENTAL", "RESEARCH"]:
        lines.append(f"| {s} | {counts.get(s, 0)} |")
    lines.append("")
    lines.append("---")
    lines.append("")

    # group by domain preserving order
    current_domain = None
    for tid, key, dtitle, ttitle, deps, status in tasks:
        if key != current_domain:
            current_domain = key
            lines.append(f"## {dtitle} (`{key}-*`)")
            lines.append("")
        depstr = ", ".join(d if "-" in d and d.split("-")[0] in dict((k, 1) for k, _, _ in DOMAINS) else f"{key}-{d}" for d in deps) or "—"
        lines.append(f"### [{status}] {tid} — {ttitle}")
        lines.append(f"- depends: {depstr}")
        lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines).rstrip() + "\n")
    print(f"wrote {OUT}: {total} tasks")

if __name__ == "__main__":
    main()
